on:
  release:
    types: [published]
name: Release
jobs:
  release:
    strategy:
      matrix:
        os: [linux, darwin, windows]
    env:
      GOARCH: amd64
      GOOS: ${{ matrix.os }}
    name: release
    runs-on: ${{ matrix.os == 'darwin' && 'macos-latest' || 'ubuntu-latest'}}
    outputs:
      sha_linux: ${{ steps.shasum.outputs.sha_linux }}
    steps:
      - uses: actions/checkout@main
      - name: Use Go 1.16.x
        uses: actions/setup-go@v2
        with:
          go-version: '~1.16.0'
      - name: Build
        if: ${{ matrix.os != 'darwin' }}
        run: go build -o mob${{ matrix.os == 'windows' && '.exe' || '' }}
        env:
          GOOS: ${{ matrix.os }}
      - name: Build
        if: ${{ matrix.os == 'darwin' }}
        run: >
          GOARCH=amd64 go build -o mob_amd64 && GOARCH=arm64 go build -o mob_arm64 && lipo -create -output mob mob_amd64 mob_arm64
        env:
          GOOS: ${{ matrix.os }}
      - name: Create release artifacts using .github/build
        run: .github/build
        env:
          VERSION: ${{ github.event.release.tag_name }}
      - name: Upload artifacts to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "*{.tar.gz,_checksum.txt}"
          tag: ${{ github.event.release.tag_name }}
          file_glob: true
      - name: Set SHA
        if: matrix.os == 'darwin' || matrix.os == 'linux'
        id: shasum
        run: |
          echo ::set-output name=sha_${{matrix.os}}_::"$(shasum -a 256 *.tar.gz | awk '{printf $1}')"