on:
  release:
    types: [published]
name: Release
jobs:
  release:
    strategy:
      matrix:
        os: [linux, darwin, windows]
        arch: [ amd64 ]
        include:
          - os: darwin
            arch: arm64
    env:
      GOARCH: ${{ matrix.arch }}
      GOOS: ${{ matrix.os }}
    name: release
    runs-on: ubuntu-latest
    outputs:
      sha_linux: ${{ steps.shasum.outputs.sha_linux }}
    steps:
      - uses: actions/checkout@main
      - name: Use Go 1.16.x
        uses: actions/setup-go@v2
        with:
          go-version: '~1.16.0'
      - name: Test
        if: matrix.arch == 'amd64'
        run: go test
        env:
          GOOS: linux # the tests will only run if the os matches the os of the system of run-on
      - name: Build
        run: go build -o mob${{ matrix.os == 'windows' && '.exe' || '' }}
        env:
          GOOS: ${{ matrix.os }}
      - name: Create release artifacts using .github/build
        run: .github/build
        env:
          VERSION: ${{ github.event.release.tag_name }}
      - name: Upload artifacts to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "*{.tar.gz,_checksum.txt}"
          tag: ${{ github.event.release.tag_name }}
          file_glob: true
      - name: Set SHA
        if: matrix.os == 'darwin' || matrix.os == 'linux'
        id: shasum
        run: |
          echo ::set-output name=sha_${{matrix.os}}_${{matrix.arch}}::"$(shasum -a 256 *.tar.gz | awk '{printf $1}')"